project:
  name: asdf

#ehcache
cache:
  max_bucket: 10000  
  item_limit_szie: 1000 
  time_to_idle: 10 
  time_to_live: 10

spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
  datasource:
    url: jdbc:mysql://172.21.135.197:3306/ose?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ose
    password: dhtpdns0987!
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE
        
      hibernate:
        cache:
        use_second_level_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        #show_sql: true   # sysout log
        use_sql_comments: true
        ddl-auto: create



#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true

#  ehcache by xml
#  cache:
#    jcache:
#      config: classpath:ehcache.xml

jackson:
    serialization:
      fail-on-empty-beans: false


#logging  
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        type: TRACE   # Show Query Parameter
        SQL: DEBUG    # Logger


#actuator        
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    cache:
      instrument: true
